name: Run Tests, Build and Push TestPyPi on any Push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
        with: # needed for tags for dunamai
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set version with dunamai
        run: |
          #python -m venv env
          #source env/bin/activate
          pip install --upgrade pip
          pip install --user dunamai
          echo __version__=\"`dunamai from git --format "{base}.dev{distance}" `\" > magic_duckdb/_version.py
          echo __commit__=\"`git rev-parse HEAD`\" >> magic_duckdb/_version.py
          echo __commit_short__=\"`git rev-parse --short HEAD`\" >> magic_duckdb/_version.py
          # display information for debugging
          cat magic_duckdb/_version.py
          git tag
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pytest
          if [ -f requirements_dev.txt ]; then pip install --user -r requirements_dev.txt; fi
          pip install --user .
      - name: Ruff Check
        run: |
          ruff check magic_duckdb --config pyproject.toml
      - name: Test with pytest
        run: |
          pytest
      - name: Build
        run: |
          pip wheel --no-deps -w dist .
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
