# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3
        with: # needed for tags for dunamai
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set version with dunamai
        run: |
          pip install --upgrade pip
          pip install --user dunamai
          export VFILE=$(basename ${{ github.repository }})/_version.py

          echo __version__=\"`dunamai from git `\" > $VFILE
          echo __commit__=\"`git rev-parse HEAD`\" >> $VFILE
          echo __commit_short__=\"`git rev-parse --short HEAD`\" >> $VFILE
          # display information for debugging
          cat $VFILE
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pytest
          if [ -f requirements_dev.txt ]; then pip install --user -r requirements_dev.txt; fi
          pip install --user .
      - name: Ruff Check
        run: |
          pip install --upgrade ruff
          ruff check magic_duckdb --config pyproject.toml
      - name: Test with pytest
        run: |
          pytest
      - name: Build
        run: |
          pip wheel --no-deps -w dist .
      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PATMDG }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*.whl
          asset_name: wheels.zip
          asset_content_type: application/zip
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
